# obtained using 'ros2 run tf2_ros tf2_echo os_lidar blueview'
# transfrom from cloud2 to cloud1 frame
transform:
  matrix: 
    - [-0.750, 0.500, 0.433, 0.514]
    - [0.433, 0.866, -0.250, 0.003]
    - [-0.500, -0.000, -0.866, -1.549]
    - [0.000, 0.000, 0.000, 1.000]
ros:
  lidar_cloud_topic: "/ouster/points"
  sonar_cloud_topic: "/blueview/point2/leading"
  output_cloud_topic: "/points/fusion"
  target_frame: "os_lidar"