# obtained using 'ros2 run tf2_ros tf2_echo os_lidar blueview'
# transfrom from cloud2 to cloud1 frame
# transform:
#   translation:
#     x: 0.513
#     y: 0.000
#     z: -1.549
#   rotation:
#     x: 0.000
#     y: 0.966
#     z: 0.000
#     w: 0.259
transform:
  matrix: 
  -  [-0.866, -0.000, 0.500, 0.513]
  -  [-0.000,  1.000, -0.000, -0.000]
  -  [-0.500, -0.000, -0.866, -1.549]
  -  [0.000,  0.000,  0.000,  1.000]

ros:
  lidar_cloud_topic: "/ouster/points"
  sonar_cloud_topic: "/blueview/points2"
  output_cloud_topic: "/points/fusion"
  target_frame: "os_lidar"