acoustic3d_edge_vertical:
  ros__parameters:  
    use_sim_time: true
    sonar:
      topic: "/blueview/sonar_image"
      threshold: 130.
      min_range: 0.7
      sound_speed: 1500. # m/s. Set to zero to use the one given in message
      sound_speed_actual: 1482.42 # m/s. Set to None to use the one given in message
      pitch: 0.0 # degrees
    method:
      leading_edge: True
      falling_edge: False
    denoise:
      standard: True
      open: 0 # 0 to disable. Oherwise number of iterations
      RANSAC: True
      MAD: False
    output:
      topic: "/sonar_cloud_vertical"
      frame_id: "blueview"
      visualize: False
      folder: "/home/rosdev/ros2_ws/src/images/vertical"