acoustic3d_edge_vertical:
  ros__parameters:  
    use_sim_time: true
    sonar:
      topic: "/blueview/sonar_image"
      threshold: 100.
      min_range: 0.1
      sound_speed: 1500. # m/s. Set to zero to use the one given in message
      sound_speed_actual: 1450.97 # m/s. Set to None to use the one given in message
      denoise:
        enable: True
      pivot: 0.0 # degrees
    method:
      leading_edge: True
      falling_edge: False
    output:
      topic: "/sonar_cloud_vertical"
      frame_id: "blueview"
      visualize: False
      folder: "./log/images/vertical"