acoustic3d_edge_horizontal:
  ros__parameters:  
    use_sim_time: true
    sonar:
      topic: "/oculus/sonar_image"
      threshold: 60.
      min_range: 0.5
      sound_speed: 1438.39 # m/s. Set to zero to use the one given in message
      sound_speed_actual: 1450.97 # m/s. Set to None to use the one given in message
      denoise:
        enable: True
        median_filter: 3
      pitch: 10.0 # degrees
    method:
      leading_edge: True
      falling_edge: False
    output:
      topic: "/sonar_cloud_horizontal"
      frame_id: "oculus"
      visualize: False
      folder: "./log/images/horizontal"